app:
  random-seed: ${RANDOM_SECRET}
  shuffle-max-attempts: 100
  notification:
    reminders:
      days: [7, 3, 1]
    schedule:
      time: "10:00"
  jwt:
    secret: ${JWT_SECRET}
  refresh:
    expiration: 604800000  # 7day
  mail:
    confirm:
      subject: "Подтверждение регистрации"
      text:
        pattern: "Здравствуйте, {0}!\nВаш код для подтверждения регистрации: {1}"
        number-of-variables: 2
      from: "${MAIL_USERNAME}@yandex.ru"
    notification:
      subject: "Напоминание о мероприятии"
      text:
        pattern: "Здравствуйте, {0}!\nНапоминаем, что {1} обмен подарками в группе {2}. {3}, чтобы купить подарок!"
        number-of-variables: 4
      from: "${MAIL_USERNAME}@yandex.ru"

spring:
  jpa:
    hibernate.ddl-auto: update
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
