app:
  handle-all-exceptions: true
  notification:
    type: mail
  jwt:
    expiration: 900000
  avatars:
    storage-path: ./avatars
  confirmation:
    expiration: 900000
    transport: mail
    length: 5
    alphabet: 0123456789

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
