app:
  handle-all-exceptions: false
  notification:
    type: ${NOTIFICATION_TRANSPORT:log}
  jwt:
    expiration: 36000000
  avatars:
    storage-path: ./avatars
  confirmation-transport: ${CONFIRMATION_TRANSPORT:log}

spring:
  datasource:
    url: jdbc:h2:file:./${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: optional:file:dev.env[.properties]
