app:
  shuffle-max-attempts: 100
  notification:
    reminders:
      days: [7, 3, 1]
  jwt:
    secret: ${JWT_SECRET}
  refresh:
    expiration: 604800000  # 7day

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
