app:
  shuffle-max-attempts: 100
  notification:
    reminders:
      days: [7, 3, 1]
  jwt:
    secret: ${JWT_SECRET}
  refresh:
    expiration: 604800000  # 7day

spring:
  jpa:
    hibernate.ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
